### ISSUE TITLE
Implement `Animation` and `Transaction` structs

### ISSUE THREAD

**Issue by MaxDesiatov** [TokamakUI/Tokamak#154]
I think the basic stuff should be implementable with CSS transitions, but there may be some limitations. Still worth trying to implement it in my opinion.

**Comment by carson-katri** [comment]
SwiftUI relies on `Transaction`s to handle animation. If you want to match the SwiftUI API, then Transaction will be necessary.

**Comment by carson-katri** [comment]
It may be possible to do this using [Web Animations](https://caniuse.com/#feat=web-animation), as most/all major browsers have at least some support for it. Otherwise, it may be tricky considering CSS animations have to be specified in a stylesheet, and it would be more difficult to manipulate that at runtime. Here's a [post on web animations](https://webkit.org/blog/10266/web-animations-in-safari-13-1/) on the WebKit blog.

Another solution would be having TokamakCore handle animations entirely, and just keep redrawing views with the updated values at a set framerate.

**Comment by MaxDesiatov** [comment]
I hope we can avoid scheduling animations manually, I reckon that would be highly inefficient. Especially because crossing the Swift<->JavaScript bridge is quite costly, and this cost will accumulate quite quickly to a noticeable lag when these bridged calls are repeated for every frame.

**Comment by MaxDesiatov** [comment]
What looks like a sensible approach to me is the reliance on the Web Animations API through [a polyfill](https://github.com/web-animations/web-animations-js), but I'm very open to a better solution 🤔

**Comment by MaxDesiatov** [comment]
What looks like a sensible approach to me is the reliance on the Web Animations API through [a polyfill](https://github.com/web-animations/web-animations-js), but I'm very open to a better solution 🤔

**Comment by carson-katri** [comment]
Yes, I agree.
